/** Named icon exports for script imports (legacy alias names). */
export {
  ArrowLeft,
  ArrowRight,
  Box,
  Bot,
  Brush,
  Check,
  Copy,
  Cpu,
  Crosshair,
  Download,
  FileText as Document,
  Film,
  Copy as DocumentCopy,
  Copy as CopyDocument,
  FolderCheck,
  FolderCheck as FolderChecked,
  Filter,
  Headphones,
  Headphones as Headset,
  Image as Picture,
  Image as PictureFilled,
  Key,
  Library,
  Loader2 as Loading,
  ListOrdered,
  Menu,
  Mic as Microphone,
  Monitor,
  MoreHorizontal as MoreFilled,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw as Refresh,
  Search,
  Settings as Setting,
  Sparkles as MagicStick,
  Star,
  Trash2 as Delete,
  Upload,
  Video,
  Play as VideoPlay,
  Video as VideoCamera,
  Wand2,
  Wrench as Tools,
  X as Close,
  Crosshair as Aim,
  Grid3x3 as Grid,
  ZoomIn,
} from 'lucide-vue-next';
