import type { App, Component } from 'vue';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Box,
  Bot,
  Brush,
  Check,
  ChevronDown,
  ChevronRight,
  CircleDot,
  CircleHelp,
  Clock,
  Copy,
  Cpu,
  Crosshair,
  Download,
  FileCode,
  FileText,
  Film,
  Filter,
  FolderCheck,
  FolderOpen,
  Globe,
  Grid3x3,
  Headphones,
  Image,
  Key,
  Library,
  Link2,
  Loader2,
  ListOrdered,
  Menu,
  Mic,
  Monitor,
  MoreHorizontal,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  Sparkles,
  Star,
  StopCircle,
  Tags,
  Terminal,
  Trash2,
  Upload,
  UserRound,
  Video,
  Wand2,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-vue-next';

function aliases(icon: Component, names: string[]): Record<string, Component> {
  const out: Record<string, Component> = {};
  for (const n of names) out[n] = icon;
  return out;
}

/** Studio + EP legacy names → Lucide components */
export const dqIconComponents: Record<string, Component> = {
  ...aliases(Cpu, ['Cpu', 'cpu']),
  ...aliases(Settings, ['Settings', 'Setting', 'setting']),
  ...aliases(Pencil, ['Pencil', 'edit-pen', 'edit']),
  ...aliases(ZoomIn, ['ZoomIn', 'zoom-in']),
  ...aliases(ZoomOut, ['ZoomOut', 'zoom-out']),
  ...aliases(Wand2, ['Wand2', 'magic-stick']),
  ...aliases(Loader2, ['Loader2', 'Loading', 'loading']),
  ...aliases(ListOrdered, ['ListOrdered', 'TaskQueue', 'task-queue']),
  ...aliases(FileText, ['FileText', 'document', 'Document']),
  ...aliases(Film, ['Film', 'film']),
  ...aliases(Trash2, ['Trash2', 'Delete', 'delete']),
  ...aliases(Image, ['Image', 'Picture', 'picture-filled', 'PictureFilled']),
  ...aliases(Clock, ['Clock', 'clock']),
  ...aliases(RefreshCw, ['RefreshCw', 'Refresh', 'refresh']),
  ...aliases(Brush, ['Brush', 'brush']),
  ...aliases(Tags, ['Tags', 'collection-tag']),
  ...aliases(ArrowUp, ['ArrowUp', 'arrow-up']),
  ...aliases(RotateCcw, ['RotateCcw', 'refresh-left']),
  ...aliases(RotateCw, ['RotateCw', 'refresh-right', 'Redo2']),
  ...aliases(Search, ['Search', 'search']),
  ...aliases(Plus, ['Plus', 'plus']),
  ...aliases(CircleHelp, ['CircleHelp', 'question-filled']),
  ...aliases(Check, ['Check', 'check']),
  ...aliases(Key, ['Key', 'key']),
  ...aliases(Star, ['Star', 'star-filled']),
  ...aliases(Upload, ['Upload', 'upload']),
  ...aliases(FolderOpen, ['FolderOpen', 'folder-opened']),
  ...aliases(Monitor, ['Monitor', 'monitor']),
  ...aliases(Video, ['Video', 'video-camera', 'VideoCamera']),
  ...aliases(Play, ['Play', 'play', 'video-play', 'VideoPlay']),
  ...aliases(Pause, ['Pause', 'pause']),
  ...aliases(Library, ['Library', 'collection']),
  ...aliases(ArrowDown, ['ArrowDown', 'arrow-down']),
  ...aliases(ChevronRight, ['ChevronRight', 'arrow-right']),
  ...aliases(Box, ['Box', 'box']),
  ...aliases(Bot, ['Bot', 'bot', 'Assistant', 'assistant']),
  ...aliases(X, ['X', 'close', 'Close']),
  ...aliases(Headphones, ['Headphones', 'headset', 'Headset']),
  ...aliases(Crosshair, ['Crosshair', 'Aim']),
  ...aliases(Wrench, ['Wrench', 'Tools']),
  ...aliases(FolderCheck, ['FolderCheck', 'FolderChecked']),
  ...aliases(Grid3x3, ['Grid3x3', 'Grid']),
  ...aliases(Menu, ['Menu']),
  ...aliases(Mic, ['Mic', 'Microphone']),
  ...aliases(Sparkles, ['Sparkles', 'MagicStick']),
  ...aliases(MoreHorizontal, ['MoreHorizontal', 'MoreFilled']),
  ...aliases(Download, ['Download', 'download']),
  ...aliases(Copy, ['Copy', 'CopyDocument', 'DocumentCopy']),
  ...aliases(Filter, ['Filter']),
  ...aliases(ArrowLeft, ['ArrowLeft']),
  ...aliases(ArrowRight, ['ArrowRight']),
  ...aliases(UserRound, ['UserRound', 'user-round']),
  ...aliases(Terminal, ['Terminal', 'terminal']),
  ...aliases(Globe, ['Globe', 'globe']),
  ...aliases(FileCode, ['FileCode', 'file-code']),
  ...aliases(Link2, ['Link2', 'Link', 'link']),
  ...aliases(StopCircle, ['StopCircle', 'stop-circle']),
  ...aliases(ChevronDown, ['ChevronDown', 'chevron-down']),
  ...aliases(CircleDot, ['CircleDot', 'circle-dot']),
};

export function registerDqIcons(app: App) {
  for (const [name, component] of Object.entries(dqIconComponents)) {
    app.component(name, component);
  }
}
